- become: yes
  file:
    name: "/etc/update-motd.d/{{ item }}"
    state: absent
  with_items:
    - "10-help-text"
    - "51-cloudguest"
    - "90-updates-available"

- name: Motd message
  become: yes
  template:
    src: templates/99-nodes.j2
    dest: /etc/update-motd.d/99-nodes
    mode: 0777
