ansible_user: ubuntu
aws_account: 147258760518

public_keys:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCWYwfgvavnIIOB9Ah6fbFDY0UpLQ0YUgRKkANN38+DDW6IwVu2i5b1g9ndzRBoNxyzhVnlr0zFPVkgygqvO0Hy5GVm0pZFgS4AYGt9bcE52QjHoXwQvJTKk12UPlWSsWOJCK2doTc3kpLBKRXXQVjzRrJkV4iOryugJ/nML/Ta51GOW/f7i9sPFTdXbGN9T5OVPQz2uHzcGIF/vGF6MdNwCNYDraBxPz7zZ+KC2g4Z5W8RRdxkbM9ymN9YIOgpZqRshdEwjL8hGwBYsprh4VPssWZuqoSkqprl8lMkCLvWNjp7QLEqH+qjL7+vZqzmTviDLlgJmZjsW0Udx4uH3VsX raidentestnet"
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCsYB5ZRFwsLHZbTVQw57rxg3E+PPIL+D1jHDblMUJUILc0/FiJ8ey2pjUt4EMy0m1+u/h25Y7ZAbknkH7YqqD8jGiupXFVLVBbjzZX/MqFs0eNEodLPZ942QHumIuD0rBlpaZyDvNCCu9udrUzLx9XwIN7p3RjO90NKLOQ+Evhtibe2DrJadjbGRVwgXbtSjGdh1+ZYi/fj/8Suu88LrxwGDIIIT6uOfUorHUzgTrSJMzrcIPVOIgIJEkZkmimHNw3CEr6/o+T62kIkfSW5CZty9zBm2lIcwzSeQk1lQuIeunn7naTu6hJbF8pGZIDRqk8Sb2+IccaIQylDwVHj2xU9nRqggctAF9F1W3+yXK91/0CmzTa5i7O98N6YsVRyCGuTLw4BMU956XMM9f32ZbTbhutBkbqRkowNI5ia+uCuXOK/2Ktqnk08vF7+DtOy7cmVHaY7O8Ea/5U6z0ZVbxg5DlVwA8w2dsP48Y6TjQ99k8NKkpFVREhFXeAnuiDQsGG9L3HsNCAAk6i11Oe4XY/WHMPpMjJ3Mb4zrXSSoUD2ekwnENbKcCD5vLfRGObEuPQC7Wg6EkaT2DdGTmXkAdLkv8knzVybgtbxyRb0yDXtHxSCMaWZDwZ6REwOO14TP7qBCYGiyNEgSRGIOR8901VUjbW2yhKQXqnS4nJFlXP+w== lefteris@archdesktop-2015-08-16"

# either "geth" or "parity"
eth_node_type: geth
data_volume_dir: "/data"

docker_channel: edge
docker_version: "17.05.0-ce"

docker_repo_empty:      "{{ aws_account }}.dkr.ecr.us-east-1.amazonaws.com/brainbot/empty"
docker_repo_eth_parity: "parity/parity:beta"
docker_repo_eth_geth:   "{{ aws_account }}.dkr.ecr.us-east-1.amazonaws.com/brainbot/geth-testnet"
docker_repo_mkkeystore: "{{ aws_account }}.dkr.ecr.us-east-1.amazonaws.com/brainbot/mkkeystore"
docker_repo_raiden:     "{{ aws_account }}.dkr.ecr.us-east-1.amazonaws.com/brainbot/raiden"

raiden_root: /etc/raiden

echo_node_token_address: "0x0f114A1E9Db192502E7856309cc899952b3db1ED"
