export const tokenabi = `[{'constant': True,
'inputs': [],
'name': 'name',
'outputs': [{'name': '', 'type': 'string'}],
'payable': False,
'type': 'function'},
{'constant': False,
'inputs': [{'name': '_spender', 'type': 'address'},
 {'name': '_value', 'type': 'uint256'}],
'name': 'approve',
'outputs': [{'name': 'success', 'type': 'bool'}],
'payable': False,
'type': 'function'},
{'constant': True,
'inputs': [],
'name': 'totalSupply',
'outputs': [{'name': '', 'type': 'uint256'}],
'payable': False,
'type': 'function'},
{'constant': False,
'inputs': [{'name': '_from', 'type': 'address'},
 {'name': '_to', 'type': 'address'},
 {'name': '_value', 'type': 'uint256'}],
'name': 'transferFrom',
'outputs': [{'name': 'success', 'type': 'bool'}],
'payable': False,
'type': 'function'},
{'constant': True,
'inputs': [],
'name': 'decimals',
'outputs': [{'name': '', 'type': 'uint8'}],
'payable': False,
'type': 'function'},
{'constant': True,
'inputs': [],
'name': 'version',
'outputs': [{'name': '', 'type': 'string'}],
'payable': False,
'type': 'function'},
{'constant': True,
'inputs': [{'name': '_owner', 'type': 'address'}],
'name': 'balanceOf',
'outputs': [{'name': 'balance', 'type': 'uint256'}],
'payable': False,
'type': 'function'},
{'constant': True,
'inputs': [],
'name': 'symbol',
'outputs': [{'name': '', 'type': 'string'}],
'payable': False,
'type': 'function'},
{'constant': False,
'inputs': [{'name': '_to', 'type': 'address'},
 {'name': '_value', 'type': 'uint256'}],
'name': 'transfer',
'outputs': [{'name': 'success', 'type': 'bool'}],
'payable': False,
'type': 'function'},
{'constant': False,
'inputs': [{'name': '_spender', 'type': 'address'},
 {'name': '_value', 'type': 'uint256'},
 {'name': '_extraData', 'type': 'bytes'}],
'name': 'approveAndCall',
'outputs': [{'name': 'success', 'type': 'bool'}],
'payable': False,
'type': 'function'},
{'constant': True,
'inputs': [{'name': '_owner', 'type': 'address'},
 {'name': '_spender', 'type': 'address'}],
'name': 'allowance',
'outputs': [{'name': 'remaining', 'type': 'uint256'}],
'payable': False,
'type': 'function'},
{'inputs': [{'name': '_initialAmount', 'type': 'uint256'},
 {'name': '_tokenName', 'type': 'string'},
 {'name': '_decimalUnits', 'type': 'uint8'},
 {'name': '_tokenSymbol', 'type': 'string'}],
'type': 'constructor'},
{'payable': False, 'type': 'fallback'},
{'anonymous': False,
'inputs': [{'indexed': True, 'name': '_from', 'type': 'address'},
 {'indexed': True, 'name': '_to', 'type': 'address'},
 {'indexed': False, 'name': '_value', 'type': 'uint256'}],
'name': 'Transfer',
'type': 'event'},
{'anonymous': False,
'inputs': [{'indexed': True, 'name': '_owner', 'type': 'address'},
 {'indexed': True, 'name': '_spender', 'type': 'address'},
 {'indexed': False, 'name': '_value', 'type': 'uint256'}],
'name': 'Approval',
'type': 'event'}]`;
