- hosts: name_raiden_testnet
  gather_facts: no
  become: yes
  roles:
    - ssh_keys
    - hostname
    - docker

- hosts: role_eth
  gather_facts: no
  roles:
    - eth_node

- hosts: role_raiden
  gather_facts: no
  roles:
    - raiden

- hosts: role_infrastructure
  gather_facts: no
  roles:
    - logstash

- hosts: name_raiden_testnet
  gather_facts: no
  roles:
    - role: motd_info
      display_groups:
        Eth: role_eth
        Raiden: role_raiden
        Infrastructure: role_infrastructure
    - role: hosts_file
      display_groups:
        Eth: role_eth
        Raiden: role_raiden
        Infrastructure: role_infrastructure

- hosts: name_raiden_testnet
  gather_facts: no
  tasks:
    - debug:
        msg: "{{ private_ip }}: {{ hostname }}"
