- hosts: role_eth
  gather_facts: no
  tags:
    - eth
  tasks:
    - name: Stop container
      docker_container:
        name: "{{ item }}"
        state: stopped
      ignore_errors: yes
      with_items:
        - geth
        - parity

    - name: Destroy eth data dir
      become: true
      file:
        name: "{{ data_volume_dir }}/{{ item }}"
        state: absent
      with_items:
        - geth
        - parity

    - name: Start container
      docker_container:
        name: "{{ eth_node_type }}"
        state: started
      ignore_errors: yes

- hosts: role_raiden
  gather_facts: no
  tags:
    - raiden
  tasks:
    - name: Stop container
      docker_container:
        name: "raiden"
        state: stopped
      ignore_errors: yes

    - name: Destroy raiden data dir
      become: true
      file:
        name: "{{ raiden_root }}"
        state: absent

    - name: Start container
      docker_container:
        name: "raiden"
        state: started
      ignore_errors: yes
