- hosts: role_raiden
  gather_facts: no
  roles:
    - keystore
  tasks:
    - template:
        src: files/templates/eth_addresses.j2
        dest: /tmp/testnet_eth_addresses
      delegate_to: 127.0.0.1
      run_once: true

    - debug:
        msg: "Output in /tmp/testnet_eth_addresses"
      delegate_to: 127.0.0.1
      run_once: true
