- hosts: name_raiden_testnet
  gather_facts: no
  become: yes
  roles:
    - hostname
    - docker

- hosts: role_eth
  gather_facts: no
  roles:
    - eth_node

- hosts: role_raiden
  gather_facts: no
  roles:
    - raiden

- hosts: name_raiden_testnet
  gather_facts: no
  roles:
    - role: motd_info
      display_groups:
        Eth: role_eth
        Raiden: role_raiden
    - role: hosts_file
      display_groups:
        Eth: role_eth
        Raiden: role_raiden

- hosts: name_raiden_testnet
  gather_facts: no
  tags:
    - roles
  tasks:
    - debug:
        msg: "{{ private_ip }}: {{ hostvars[inventory_hostname]['tags.Role'].lower() }}_{{ '{:02d}'.format(private_ip.rpartition('.')[2]|int) }}"
        msg: "{{ private_ip }}: {{ hostname }}"
