import pytest


@pytest.fixture(autouse=True)
def override_capture_setting_for_hypothesis_tests(request):
    """override the general setting to see failed paths generated by Hypothesis """
    request.config.option.showcapture = 'all'
