# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raiden/resolver/resolver.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='raiden/resolver/resolver.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1eraiden/resolver/resolver.proto\"v\n\x0eResolveRequest\x12\x12\n\x04hash\x18\x01 \x01(\tR\x04hash\x12\x18\n\x07timeout\x18\x02 \x01(\rR\x07timeout\x12\x1e\n\nheight_now\x18\x03 \x01(\rR\nheight_now\x12\x16\n\x06\x61mount\x18\x04 \x01(\x03R\x06\x61mount\"-\n\x0fResolveResponse\x12\x1a\n\x08preimage\x18\x01 \x01(\tR\x08preimage2B\n\x0cHashResolver\x12\x32\n\x0bResolveHash\x12\x0f.ResolveRequest\x1a\x10.ResolveResponse\"\x00\x62\x06proto3')
)




_RESOLVEREQUEST = _descriptor.Descriptor(
  name='ResolveRequest',
  full_name='ResolveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash', full_name='ResolveRequest.hash', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='hash', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeout', full_name='ResolveRequest.timeout', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='timeout', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height_now', full_name='ResolveRequest.height_now', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='height_now', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='ResolveRequest.amount', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='amount', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=152,
)


_RESOLVERESPONSE = _descriptor.Descriptor(
  name='ResolveResponse',
  full_name='ResolveResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='preimage', full_name='ResolveResponse.preimage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='preimage', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=199,
)

DESCRIPTOR.message_types_by_name['ResolveRequest'] = _RESOLVEREQUEST
DESCRIPTOR.message_types_by_name['ResolveResponse'] = _RESOLVERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ResolveRequest = _reflection.GeneratedProtocolMessageType('ResolveRequest', (_message.Message,), dict(
  DESCRIPTOR = _RESOLVEREQUEST,
  __module__ = 'raiden.resolver.resolver_pb2'
  # @@protoc_insertion_point(class_scope:ResolveRequest)
  ))
_sym_db.RegisterMessage(ResolveRequest)

ResolveResponse = _reflection.GeneratedProtocolMessageType('ResolveResponse', (_message.Message,), dict(
  DESCRIPTOR = _RESOLVERESPONSE,
  __module__ = 'raiden.resolver.resolver_pb2'
  # @@protoc_insertion_point(class_scope:ResolveResponse)
  ))
_sym_db.RegisterMessage(ResolveResponse)



_HASHRESOLVER = _descriptor.ServiceDescriptor(
  name='HashResolver',
  full_name='HashResolver',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=201,
  serialized_end=267,
  methods=[
  _descriptor.MethodDescriptor(
    name='ResolveHash',
    full_name='HashResolver.ResolveHash',
    index=0,
    containing_service=None,
    input_type=_RESOLVEREQUEST,
    output_type=_RESOLVERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HASHRESOLVER)

DESCRIPTOR.services_by_name['HashResolver'] = _HASHRESOLVER

# @@protoc_insertion_point(module_scope)
