#!/usr/bin/env python
import os
import sys

import logstash
from ethereum import slogging
from pkg_resources import load_entry_point

"""
Modified entrypooint script to inject logstash handler.
"""


if __name__ == "__main__":
    if 'RAIDEN_LOGSTASH_HOST' in os.environ:
        slogging.configure()
        slogging.rootLogger.addHandler(
            logstash.UDPLogstashHandler(
                os.environ.get('RAIDEN_LOGSTASH_HOST'),
                int(os.environ.get('RAIDEN_LOGSTASH_PORT', 9595)),
                version=1
            )
        )

    sys.exit(
        load_entry_point('raiden', 'console_scripts', 'raiden')()
    )
