#!usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'raiden==0.0.5','console_scripts','raiden'
__requires__ = 'raiden==0.0.5'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
            load_entry_point('raiden==0.0.5', 'console_scripts', 'raiden')()
            )

