- name: Create storage fs
  become: yes
  filesystem:
    dev: /dev/xvdb
    fstype: ext4

- name: Mount storage fs
  become: yes
  mount:
    fstype: ext4
    path: "{{ data_volume_dir }}"
    src: /dev/xvdb
    state: mounted
