- name: Traefik config dir
  become: yes
  file:
    path: /etc/traefik
    state: directory

- name: Traefik config file
  become: yes
  template:
    src: templates/traefik.toml.j2
    dest: /etc/traefik/traefik.toml

- name: Traefik raiden proxy config
  become: yes
  template:
    src: templates/rules.toml.j2
    dest: /etc/traefik/rules.toml

- name: Traefik docker container
  docker_container:
    name: traefik
    restart_policy: always
    pull: yes
    image: "{{ docker_repo_traefik }}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/traefik:/etc/traefik"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    command: "-l DEBUG"
