- name: Create keystore path
  become: yes
  file:
    name: "{{ keystore_root }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: 0700

- name: Keystore password file
  template:
    src: templates/password.j2
    dest: "{{ keystore_root }}/password"
    owner: "{{ ansible_user }}"
    mode: 0400
    force: yes

- set_fact:
    keystore_filename: "{{ keystore_root }}/UTC--{{ keystore_file_date }}--{{ private_ip }}"

- name: Check keystore file
  stat:
    path: "{{ keystore_filename }}"
  register: keystore_file

- name: Create keystore file
  docker_container:
    name: create_keystore
    image: "{{ docker_repo_mkkeystore }}"
    recreate: yes
    pull: yes
    command:
      - "-o"
      - "/data"
      - "--key-label"
      - "{{ private_ip }}"
      - "--date-string"
      - "2017-07-01"
      - "{{ keystore_password }}"
      - "{{ private_ip }}"
      - "{{ keystore_priv_seed }}"
    state: started
    volumes:
      - "{{ keystore_root }}:/data"
      - /tmp:/tmp
  when: keystore_file.stat.exists == False

- name: Wait for keystore generation
  command: docker wait create_keystore
  when: keystore_file.stat.exists == False

- name: Remove keystore helper container
  docker_container:
    name: create_keystore
    state: absent
  when: keystore_file.stat.exists == False

- name: Fetch keystore address
  command: "cat {{ keystore_filename }}"
  changed_when: no
  register: keystore_content

- set_fact:
    keystore_content: "{{ keystore_content.stdout|from_json }}"

- set_fact:
    keystore_address: "{{ keystore_content['address'] }}"
