- name: Hostname
  hostname:
    name: "{{ hostvars[inventory_hostname]['tags.Role'].lower() }}_{{ '{:02d}'.format(private_ip.rpartition('.')[2]|int) }}"

- name: Hostname file
  become: yes
  template:
    src: templates/hostname.j2
    dest: /etc/hostname
