- name: Logstash config dir
  become: yes
  file:
    path: /etc/logstash
    state: directory

- name: Logstash config file
  become: yes
  copy:
    src: files/logstash.conf
    dest: /etc/logstash/logstash.conf

- name: Elasticsearch container
  docker_container:
    name: elasticsearch
    restart_policy: always
    pull: yes
    image: "{{ docker_repo_elasticsearch }}"
    volumes:
      - "{{ data_volume_dir }}/es:/usr/share/elasticsearch/data"
    env:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

- name: Logstash docker container
  docker_container:
    name: logstash
    restart_policy: always
    pull: yes
    image: "{{ docker_repo_logstash }}"
    links:
      - elasticsearch:elasticsearch
    ports:
      - 9595:9595
      - 9595:9595/udp
    volumes:
      - /etc/logstash:/etc/logstash
    command: -f /etc/logstash/logstash.conf

- name: Kibana docker container
  docker_container:
    name: kibana
    restart_policy: always
    pull: yes
    image: "{{ docker_repo_kibana }}"
    links:
      - elasticsearch:elasticsearch
    ports:
      - 5601:5601
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:logs.{{ testnet_domain }}"
      traefik.frontend.entryPoints: "https"
