- name: Create eth node data dir
  become: true
  file:
    name: "{{ data_volume_dir }}/{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    mode: 0770
  with_items:
    - geth
    - parity

- name: Eth node (parity) docker container
  docker_container:
    name: parity
    state: "{{ 'started' if eth_node_type == 'parity' else 'absent' }}"
    restart_policy: always
    pull: yes
    image: "{{ docker_repo_eth_parity }}"
    ports:
      - "8545:8545"
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - "{{ data_volume_dir }}/parity:/root/.local/share/io.parity.ethereum"
    command:
      - "--chain"
      - "ropsten"
      - "--warp"
      - "--jsonrpc-interface"
      - "0.0.0.0"
      - "--jsonrpc-hosts"
      - "all"
      - "--nat"
      - "extip:{{ ansible_host }}"

- name: Eth node (geth) docker container
  docker_container:
    name: geth
    state: "{{ 'started' if eth_node_type == 'geth' else 'absent' }}"
    restart_policy: always
    pull: yes
    image: "{{ docker_repo_eth_geth }}"
    ports:
      - "8545:8545"
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - "{{ data_volume_dir }}/geth:/root/.ethereum"
