API_PATH: str = '/api/1'
API_HOST: str = 'localhost'
API_DEFAULT_PORT: int = 5002

WEB3_PROVIDER_DEFAULT: str = "http://127.0.0.1:8545"

DEFAULT_PERCENTAGE_FEE: float = 0.001

DIVERSITY_PEN_DEFAULT: float = 0.001
MAX_PATHS_PER_REQUEST: int = 25
MIN_PATH_REDUNDANCY: int = 20
PATH_REDUNDANCY_FACTOR: int = 4
